import = ["~/.config/alacritty/themes/themes/coolnight.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12

# decorations = "Buttonless"

# opacity = 0.75
# blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16
