# Package definitions for chezmoi
# Used by run_onchange_before_install-packages-*.sh.tmpl scripts

packages:
  # macOS packages installed via Homebrew
  darwin:
    brews:
      - fzf
      - fd
      - bat
      - git-delta
      - eza
      - tlrc  # tldr client
      - thefuck
      - tmux
      - tree-sitter
      - zellij
      - starship
      - zoxide
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    casks:
      - ghostty
      - sf-symbols
      - font-meslo-lg-nerd-font
      - font-sf-pro
      - font-hack-nerd-font
    taps:
      - nikitabobko/tap/aerospace

  # Linux packages by distribution family
  linux:
    # Debian/Ubuntu family
    apt:
      - fzf
      - fd-find
      - bat
      - eza
      - git-delta
      - tldr
      - tmux
      - zoxide
      - zsh-autosuggestions
      - zsh-syntax-highlighting

    # Fedora/RHEL family
    dnf:
      - fzf
      - fd-find
      - bat
      - eza
      - git-delta
      - tldr
      - tmux
      - zoxide
      - zsh-autosuggestions
      - zsh-syntax-highlighting

    # Arch family
    pacman:
      - fzf
      - fd
      - bat
      - eza
      - git-delta
      - tldr
      - tmux
      - zoxide
      - zsh-autosuggestions
      - zsh-syntax-highlighting

  # Cross-platform tools installed via curl/pip
  universal:
    - name: neovim
      check: nvim
      install: curl -sLo ~/.local/bin/nvim https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage && chmod u+x ~/.local/bin/nvim
    - name: starship
      check: starship
      install: curl -sS https://starship.rs/install.sh | sh -s -- -y -b ~/.local/bin
    - name: uv
      check: uv
      install: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: thefuck
      check: thefuck
      install: pipx install thefuck || pip3 install --user thefuck
    - name: go
      check: go
      install: curl -sL https://go.dev/dl/go1.25.4.linux-amd64.tar.gz | tar -C ~/.local -xzf - && ln -sf ~/.local/go/bin/go ~/.local/bin/go && ln -sf ~/.local/go/bin/gofmt ~/.local/bin/gofmt
    - name: black
      check: black
      install: pipx install black
    - name: isort
      check: isort
      install: pipx install isort
