#
# Golang
#
export GOPATH=$HOME/dev/go
export GOBIN=$GOPATH/bin

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  # Homebrew
  eval "$(/opt/homebrew/bin/brew shellenv)"

  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='emacsclient -nw'
export VISUAL='emacsclient -nw'
export PAGER='less'

if [[ "$OSTYPE" = linux* ]]; then
   export EDITOR='emacsclient -nw'
   export VISUAL='emacsclient -nw'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  /usr/local/opt/make/libexec/gnubin
  /opt/homebrew/Cellar/vips/bin
  $GOBIN
  $HOME/.local/bin
  $HOME/.cargo/bin
  $HOME/.emacs.d/bin
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
eval "$(/opt/homebrew/bin/brew shellenv)"
